import { useState, useMemo } from 'react'
import data from './content.json'

const STATUSES = ['', 'draft', 'approved', 'shot', 'posted', 'rejected']

export default function App() {
  const [q, setQ] = useState('')
  const [status, setStatus] = useState('')
  const [sort, setSort] = useState('id')
  const { scripts = [], sources = [], persona = {} } = data

  const rows = useMemo(() => {
    let r = scripts.filter((s) => !status || s.status === status)
    if (q.trim()) {
      const needle = q.trim()
      r = r.filter((s) =>
        [s.title_ar, s.title_en, s.hook, s.vo, s.cta, s.caption, s.inspired_by]
          .filter(Boolean).join(' ').includes(needle)
      )
    }
    const desc = sort[0] === '-'
    const key = desc ? sort.slice(1) : sort
    return [...r].sort((a, b) => {
      const x = a[key], y = b[key]
      if (typeof x === 'string') return desc ? (y > x ? 1 : -1) : (x > y ? 1 : -1)
      return desc ? y - x : x - y
    })
  }, [scripts, q, status, sort])

  return (
    <div className="wrap">
      <header>
        <h1>🦞 Prime Softworks — Content DB</h1>
        <p>كل المحتوى مخزّن في قاعدة بيانات · {scripts.length} سكريبت · {sources.length} مصادر متحللة</p>
        <p>المؤسس: أحمد · شركة سوفتوير مصرية بتتدار بالـAI · اللهجة: مصري</p>
        <span className="meta">آخر تحديث {data.generated}</span>
      </header>

      <div className="panel">
        <h3>👤 البروفايل والتفضيلات</h3>
        <p><b>البايو:</b> {persona.bio}</p>
        <p><b>بيحب يعمل:</b> {persona.likes}</p>
        <p className="nogo"><b>مش هيعمله أبداً (NO-GO):</b> {persona.no_go}</p>
        <p><b>نبرة الصوت:</b> {persona.voice_notes}</p>
      </div>

      <div className="panel">
        <h3>📊 المصادر اللي اتحللت</h3>
        <table>
          <thead><tr><th>الحساب</th><th>متابعين</th><th>ريلز متحللة</th><th>آخر استيراد</th></tr></thead>
          <tbody>
            {sources.map((s) => (
              <tr key={s.handle}>
                <td style={{ direction: 'ltr' }}>@{s.handle}</td>
                <td>{(s.followers || 0).toLocaleString()}</td>
                <td>{s.reels_analyzed || 0}</td>
                <td>{s.imported_at}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="controls">
        <input placeholder="ابحث في السكريبتات…" value={q} onChange={(e) => setQ(e.target.value)} />
        <select value={status} onChange={(e) => setStatus(e.target.value)}>
          {STATUSES.map((s) => <option key={s} value={s}>{s || 'كل الحالات'}</option>)}
        </select>
        <select value={sort} onChange={(e) => setSort(e.target.value)}>
          <option value="id">ترتيب: الأقدم</option>
          <option value="-id">الأحدث</option>
          <option value="-length_s">الأطول</option>
        </select>
      </div>

      {rows.length === 0 ? (
        <div className="empty">مفيش نتايج.</div>
      ) : (
        rows.map((r) => (
          <div className="card" key={r.id}>
            <h2>
              <span className="num">{r.id}</span> {r.title_ar}
              <span className="en">{r.title_en}</span>
            </h2>
            <div className="badges">
              <span className="b b-len">~{r.length_s || 80}s</span>
              <span className={`b b-st ${r.status}`}>{r.status}</span>
              <span className="b b-insp">{r.inspired_by}</span>
            </div>
            <div className="label l-hook">الهوك</div>
            <div className="hook">{r.hook}</div>
            <div className="label l-vo">الكلام</div>
            <div className="vo">{r.vo}</div>
            <div className="label l-cta">الـCTA</div>
            <div className="cta">{r.cta}</div>
            <div className="label l-cap">الكابشن</div>
            <div className="cap">{r.caption}<span className="tags">{r.hashtags}</span></div>
          </div>
        ))
      )}

      <div className="foot">🦞 Generated by PrimeClaw · React + Vite · data from content.db</div>
    </div>
  )
}
